// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchGithubActivity(arg1:string,arg2:string):Promise<Array<main.GithubActivity>>;

export function GetTokenExpiration(arg1:string):Promise<string>;

export function LoadConfig():Promise<main.Config>;

export function SaveConfig(arg1:main.Config):Promise<void>;
