// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

/**
 * @param {string} arg1
 * @param {string} arg2
 * @param {string} [arg3]
 * @returns {Promise<Array<domain.GithubActivity>>}
 */
export function FetchGithubActivity(arg1, arg2, arg3 = '') {
  return (/** @type {any} */ (window))['go']['main']['App']['FetchGithubActivity'](arg1, arg2, arg3 || '');
}

/**
 * @returns {Promise<Array<domain.Repository>>}
 */
export function FetchUserRepositories() {
  return (/** @type {any} */ (window))['go']['main']['App']['FetchUserRepositories']();
}

/**
 * @param {string} arg1
 * @returns {Promise<string>}
 */
export function GetTokenExpiration(arg1) {
  return (/** @type {any} */ (window))['go']['main']['App']['GetTokenExpiration'](arg1);
}

/**
 * @returns {Promise<domain.Config>}
 */
export function LoadConfig() {
  return (/** @type {any} */ (window))['go']['main']['App']['LoadConfig']();
}

/**
 * @param {domain.Config} arg1
 * @returns {Promise<void>}
 */
export function SaveConfig(arg1) {
  return (/** @type {any} */ (window))['go']['main']['App']['SaveConfig'](arg1);
}
