// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {domain} from '../models';

export function FetchGithubActivity(arg1:string,arg2:string,arg3:string):Promise<Array<domain.GithubActivity>>;

export function FetchUserRepositories():Promise<Array<domain.Repository>>;

export function GetTokenExpiration(arg1:string):Promise<string>;

export function LoadConfig():Promise<domain.Config>;

export function SaveConfig(arg1:domain.Config):Promise<void>;
