// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchGithubActivity(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchGithubActivity'](arg1, arg2, arg3);
}

export function FetchUserRepositories() {
  return window['go']['main']['App']['FetchUserRepositories']();
}

export function GetTokenExpiration(arg1) {
  return window['go']['main']['App']['GetTokenExpiration'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}
